cloud:
  aws:
    credentials:
      access-key: AKIAZQNOULR2YICI2TFC
      secret-key: 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
    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: meharet.com


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
